name: Macos-CI

on: [push, pull_request]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use cmake (default)
        run: |
          cmake -B build -D CMAKE_BUILD_TYPE=Release
          cmake --build build
          ctest --test-dir build --output-on-failure
      - name: Use cmake (debug)
        run: |
          cmake -B build  -D CMAKE_BUILD_TYPE=Debug
          cmake --build build
          ctest --test-dir build --output-on-failure