name: Ubuntu-CI

on: [push, pull_request]



jobs:
  ci:
    name: ubuntu-gcc
    runs-on: ubuntu-latest

    env:
      CC: gcc
      CXX: g++

    steps: 
      - uses: actions/checkout@v2
      - name: Use cmake (default)
        run: |
          cmake -B build -D CMAKE_BUILD_TYPE=Release
          cmake --build build
          ctest --test-dir build --output-on-failure
      - name: Use cmake (debug)
        run: |
          cmake -B build  -D CMAKE_BUILD_TYPE=Debug
          cmake --build build
          ctest --test-dir build --output-on-failure
      - name: Use cmake (sanitizers)
        run: |
          cmake -B build -D FASTPFOR_SANITIZE=ON
          cmake --build build
          ctest --test-dir build --output-on-failure